export const GET_CUSTOMER_EXPENSES_REQUEST = "GET_CUSTOMER_EXPENSES_REQUEST";
export const GET_CUSTOMER_EXPENSES_SUCCESS = "GET_CUSTOMER_EXPENSES_SUCCESS";
export const GET_CUSTOMER_EXPENSES_FAILURE = "GET_CUSTOMER_EXPENSES_FAILURE";


export const SET_CUSTOMER_EXPENSES_REQUEST = "SET_CUSTOMER_EXPENSES_REQUEST";
export const SET_CUSTOMER_EXPENSES_SUCCESS = "SET_CUSTOMER_EXPENSES_SUCCESS";
export const SET_CUSTOMER_EXPENSES_FAILURE = "SET_CUSTOMER_EXPENSES_FAILURE";


export const DELETE_CUSTOMER_EXPENSES_REQUEST = "DELETE_CUSTOMER_EXPENSES_REQUEST";
export const DELETE_CUSTOMER_EXPENSES_SUCCESS = "DELETE_CUSTOMER_EXPENSES_SUCCESS";
export const DELETE_CUSTOMER_EXPENSES_FAILURE = "DELETE_CUSTOMER_EXPENSES_FAILURE";