export const REGISTER_REQUEST="REGISTER_REQUEST"
export const REGISTER_SUCCESS="REGISTER_SUCCESS"
export const REGISTER_FAILURE="REGISTER_FAILURE"


export const LOGIN_REQUEST="LOGIN_REQUEST"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAILURE="LOGIN_FAILURE"

export const GET_USER_REQUEST="GET_USER_REQUEST";
export const GET_USER_SUCCESS="GET_USER_SUCCESS";
export const GET_USER_FAILURE="GET_USER_FAILURE";

export const SEND_ACTIVATION_MAIL_REQUEST="SEND_ACTIVATION_MAIL_REQUEST";
export const SEND_ACTIVATION_MAIL_SUCCESS="SEND_ACTIVATION_MAIL_SUCCESS";
export const SEND_ACTIVATION_MAIL_FAILURE="SEND_ACTIVATION_MAIL_FAILURE";

export const CONFIRM_ACTIVATION_REQUEST="CONFIRM_ACTIVATION_REQUEST";
export const CONFIRM_ACTIVATION_SUCCESS="CONFIRM_ACTIVATION_SUCCESS";
export const CONFIRM_ACTIVATION_FAILURE="CONFIRM_ACTIVATION_FAILURE";


export const RESET_PASSWORD_REQUEST="RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS="RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE="RESET_PASSWORD_FAILURE";


export const RESET_PASSWORD_MAIL_SEND_REQUEST="RESET_PASSWORD_MAIL_SEND_REQUEST";
export const RESET_PASSWORD_MAIL_SEND_SUCCESS="RESET_PASSWORD_MAIL_SEND_SUCCESS";
export const RESET_PASSWORD_MAIL_SEND_FAILURE="RESET_PASSWORD_FAILURE";

export const LOGOUT="LOGOUT";